[variables]
    PHP_VERSION = "8.2"
    NIXPACKS_METADATA = "php,laravel"

[phases.build]
    cmds = [
        "composer install --no-dev --optimize-autoloader",
        "php artisan key:generate --force",
        "chmod +x ./build.sh"
    ]

[phases.start]
    cmd = "bash ./build.sh && php artisan serve --host=0.0.0.0 --port=$PORT"

[variables.environment]
    APP_ENV = "production"
    APP_DEBUG = "false"
    LOG_LEVEL = "error"
